name: lang_table
description: >-
  lang_table is a dart plugin to generate string files from a source. Use
  a table to manage all multi-language resources.

version: 0.2.0
author: King Wu (@kw101) <king.wuff101@gmail.com>
homepage: https://github.com/KingWu/lang_table

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  path: ^1.8.0
  ansicolor: ^2.0.1
  http: ^0.13.1
